#Basic Spring Boot Config for Postgresql test
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lpp_local?currentSchema=usersAuth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 1919

config:
  endpoints:
    user:
      data: UserDataBase
             